config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  get 'upload' => 'images#new', :as => "upload"
  get 'membership' => 'memberships#new'
  get 'events/calendar' => 'events#calendar'
  resources :albums, :images, :events, :posts, :users
  root 'albums#index'
  get '/test' => 'memberships#test'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
	validates :event_title, :event_body, :event_date, :event_time, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :calendar, :show]
  before_action :check_authorize, only: [:new, :create, :edit, :update, :destroy]

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      flash[:notice] = "Event Saved!"
      redirect_to root_path
    else
      render 'new'
    end    
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      flash[:notice] = "Event Updated!"
      redirect_to events_path
    else
      render 'edit'
    end    
  end

  def destroy
    @event  = Event.find(params[:id])
    @event.destroy

    redirect_to events_path
  end

  def index
    @events = Event.all
  end

  def calendar
    @events = Event.all
    @events_by_date = @events.group_by(&:event_date)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:event_title, :event_body, :event_date, :event_time, :event_location)
  end

  def check_authorize
    authorize OpenStruct.new(policy_class: EventPolicy, current_user: current_user)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_eventsnav.html.erb
<div style="background-color: #efefef;">
  <br />
  <br />
  <br />
  <br />

  <div class="events-menu">
  	<center>
		<ul>
			<li>
				<%= link_to "All Events", events_path, class: "events-menu-link", style:"color: #02070a;text-decoration:none;" %>
				<div class="pipe" style="display:inline-block;height: 200;">
					|
				</div>
			</li>
			<li>
				<%= link_to "Year Calendar", events_calendar_path, class: "events-menu-link", style:"color: #02070a;text-decoration:none;" %>
			</li>
			<% if user_signed_in? %>
				<% if policy(:event).edit? %>
					<div class="pipe" style="display:inline-block;height: 200;">|</div>
					<li>
						<%= link_to "New Event", new_event_path, class: "events-menu-link", style:"color: #02070a;text-decoration:none;" %>				
					</li>
				<% end %>
			<% end %>
		</ul>
	</center>
  </div>
</div>

app/views/events/calendar.html.erb
<% provide(:events_active, 'active') %>

<div class="bg-color">
	<%= render 'eventsnav' %>
	<div class="container">
		<br />

		<div class="wrapper-bc">
			<section class="header-bc">

  				<div class="logo-and-nav-wrap">
			
					<div class="site-nav-wrap">
         				<nav class="nav-bc">
					
							<div class="single-breadcrumb-wrap">
								<span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc"><a href="/">Home</a></span>
							</div>
							<div class="single-breadcrumb-wrap">
								<span class="sep">
									<i class="fa fa-caret-right"></i>
								</span>
								<%= link_to 'Events', events_path, :class => "breadcrumb-bc" %>
							</div>					
           					<div class="single-breadcrumb-wrap">
								<span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc">Calendar</span>
							</div>
						</nav>
					</div>
				</div>
			</section>
  		</div>		

		<div id="events">
			<h2 id="month">
	    		<%= link_to "<", date: @date.prev_month %>
	    		<%= @date.strftime("%B %Y") %>
			    <%= link_to ">", date: @date.next_month %>
	  		</h2>

	  		<%= calendar @date do |date| %>
	  			<%= date.day %>
	    		<% if @events_by_date[date] %>
	      			<ul>
	        			<% @events_by_date[date].each do |event| %>
	          				<li><%= link_to event.event_title, event %></li>
	        			<% end %>
	      			</ul>
	    		<% end %>
	  		<% end %>
		</div>
	</div>
	<br/>
</div>

app/views/events/edit.html.erb
<% provide(:events_active, 'active') %>

<div class="bg-color">
	<%= render 'eventsnav' %>
	<div class="container">
		<div class="wrapper-bc">
			<section class="header-bc">
<br/>
  				<div class="logo-and-nav-wrap">
			
					<div class="site-nav-wrap">
         				<nav class="nav-bc">
					
							<div class="single-breadcrumb-wrap">
								<span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc"><a href="/">Home</a></span>
							</div>
							<div class="single-breadcrumb-wrap">
								<span class="sep">
									<i class="fa fa-caret-right"></i>
								</span>
								<%= link_to 'Events', events_path, :class => "breadcrumb-bc" %>
							</div>					
           					<div class="single-breadcrumb-wrap">
								<span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc"><%= link_to @event.event_title, event_path(@event.id) %></span>
							</div>
           					<div class="single-breadcrumb-wrap">
								<span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc">Edit</span>
							</div>							
						</nav>
					</div>
				</div>
			</section>
  		</div>		
		<br/>

		<div class="container">
			<h2>Edit <%= @event.event_title %></h2>
			<br/>
			<%= form_for @event, :html => {:multipart => true} do |f| %>

				<div class="form-group row">
					<%= f.label "event_title:" %>
					<div class="col-10">
						<%= f.text_field :event_title %>
					</div>
				</div>

				<div class="form-group row">
					<%= f.label "event_body:" %>
					<div class="col-10">
						<%= f.text_field :event_body %>	
					</div>
				</div>
					
				<div class="form-group row">
					<%= f.label "event_date:" %>
					<div class="col-10">
						<%= f.text_field :event_date %>
					</div>
				</div>

				<div class="form-group row">
					<%= f.label "event_time:" %>
					<div class="col-10">
						<%= f.time_select :event_time %>
					</div>
				</div>

				<div class="form-group row">
					<%= f.label "event_location:" %>
					<div class="col-10">
						<%= f.text_field :event_location %>	
					</div>
				</div>

					<%= f.submit "Submit", class: "btn btn-primary" %>
					<br/>
					<br/>
			<% end %>
		</div>
	</div>
</div>

app/views/events/index.html.erb
<% provide(:events_active, 'active') %>

<div class="bg-color">
	<%= render 'eventsnav' %>
	<div class="container">
		<br/>

		<div class="wrapper-bc">
			<section class="header-bc">

  				<div class="logo-and-nav-wrap">
			
					<div class="site-nav-wrap">
         				<nav class="nav-bc">
					
							<div class="single-breadcrumb-wrap">
								<span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc"><a href="/">Home</a></span>
							</div>
           					<div class="single-breadcrumb-wrap">
								<span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc">Events</span>
							</div>							
						</nav>
					</div>
				</div>
			</section>
  		</div>			
		<br />

		<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
	  		<li class="nav-item">
	    		<a class="nav-link active" id="pills-upcoming-tab" data-toggle="pill" href="#pills-upcoming" role="tab" aria-controls="pills-upcoming" aria-selected="true">Upcoming</a>
	  		</li>
	  		<li class="nav-item">
	    		<a class="nav-link" id="pills-past-tab" data-toggle="pill" href="#pills-past" role="tab" aria-controls="pills-past" aria-selected="false">Past</a>
	  		</li>
		</ul>
		
		<div class="tab-content" id="pills-tabContent">
	  		<div class="tab-pane fade show active" id="pills-upcoming" role="tabpanel" aria-labelledby="pills-upcoming-tab">
	  			<% @events.each do |event| %>
	  				<% if event.event_date >= Date.today %>
	  					<div class="container">
					    	<section class="event-calendar">
					          	<section class="result-card result-card__event">
					            	<div class="result-card__slide-container">
					              		<div class="result-card__date-wrapper">
							                <p class="result-card__event-date"><%= event.event_date.strftime("%b %d") %></p>
					                		<p class="result-card__time" style="line-height: 5;"><%= event.event_time.strftime("%I:%M %p") %></p>
					              		</div>
					              		<p class="result-card__event-issue">India</p>
					              		<div class="result-card__info-wrapper">
					                		<%= link_to event.event_title, event, :style => 'text-decoration: none;', :class => "result-card__title" %>
					                		<div class="result-card__details-wrapper">
					                  			<p class="result-card__place">
					                    			<span><%= event.event_location %></span>
					                  			</p>
					                  			<div class="result-card__keynote-wrapper">                           
					                      			<div class="result-card__keynote-eyebrow"></div>
					                      			<div class="result-card__keynote-speakers"></div>
					                  			</div>
					                		</div>
					              		</div>
					            	</div>
					          	</section>
					      	</section>
					  	</div>
					<% end %>
				<% end %>	  
			</div>
	  		
	  		<div class="tab-pane fade" id="pills-past" role="tabpanel" aria-labelledby="pills-past-tab">
	  	  		<% @events.each do |event| %>
	  				<% if event.event_date < Date.today %>
	  					<div class="container">
					    	<section class="event-calendar">
					          	<section class="result-card result-card__event">
					            	<div class="result-card__slide-container">
					              		<div class="result-card__date-wrapper">
							                <p class="result-card__event-date"><%= event.event_date.strftime("%b %d") %></p>
					                		<p class="result-card__time" style="line-height: 5;"><%= event.event_time.strftime("%I:%M %p") %></p>
					              		</div>
					              		<p class="result-card__event-issue">India</p>
					              		<div class="result-card__info-wrapper">
					                		<%= link_to event.event_title, event, :style => 'text-decoration: none;', :class => "result-card__title" %>
					                		<div class="result-card__details-wrapper">
					                  			<p class="result-card__place">
					                    			<span><%= event.event_location %></span>
					                  			</p>
					                  			<div class="result-card__keynote-wrapper">                           
					                      			<div class="result-card__keynote-eyebrow"></div>
					                      			<div class="result-card__keynote-speakers"></div>
					                  			</div>
					                		</div>
					              		</div>
					            	</div>
					          	</section>
					      	</section>
					  	</div>
					<% end %>
				<% end %>
	  		</div>
		</div>
	</div>
	<br/>
</div>

<style type="text/css">
	.result-card {
    width: 100%;
    min-height: 12.125rem;
    padding: 1.0625rem 1.25rem;
    margin-bottom: .3125rem;
    background-color: #fff;
    position: relative;
    display: block;
    float: left;
    clear: both;
}
.result-card__place, .result-card__date {
    font-family: gotham a, gotham b;
    font-weight: 400;
    font-size: .75rem;
    line-height: 1.7;
    color: #264a59;
}
.result-card__place span, .result-card__date span {
    font-family: gotham a, gotham b;
    font-weight: 500;
}
.result-card__event .result-card__event-date, .result-card__past-event .result-card__event-date {
    font-family: chronicle display a, chronicle display b;
    font-weight: 300;
    font-size: 2rem;
    line-height: .6;
    color: #75a5c0;
    margin-bottom: 1.25rem;
    display: inline-block;
    font-weight: 100;
}

.result-card__event .result-card__time, .result-card__past-event .result-card__time {
    font-family: gotham a, gotham b;
    font-weight: 500;
    font-size: .75rem;
    font-weight: 500;
    line-height: 1.3;
    color: #264a59;
    display: inline-block;
    margin-left: 1.0625rem;
}
@media screen and (min-width:1024px) {
.result-card__info-wrapper {
    float: left;
    display: block;
    margin-right: 1.94175%;
    width: 69.41748%;
    padding-left: 3.125rem;
}
}
.event-calendar {
    margin-left: -1.25rem;
    margin-right: -1.25rem;
}
.event-calendar .result-card {
    width: auto;
    float: none;
    overflow: hidden;
}
.event-calendar .result-card:after {
    content: '';
    position: absolute;
    left: 11rem;
    top: 0;
    height: 4.1875rem;
    border-right: 1px solid #616469;
    transition: all .3s ease;
}
.event-calendar .result-card__event {
    background-color: #292e35;
    padding-top: 0;
    padding-bottom: 1.5625rem;
    margin-bottom: .0625rem;
}
.event-calendar .result-card__slide-container {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-flex-wrap: wrap;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    -webkit-justify-content: flex-start;
    -ms-flex-pack: start;
    justify-content: flex-start;
    -webkit-align-items: flex-start;
    -ms-flex-align: start;
    align-items: flex-start;
    -webkit-align-content: flex-start;
    -ms-flex-line-pack: start;
    align-content: flex-start;
    height: 100%;
    width: 100%;
    position: relative;
}
.event-calendar .result-card__date-wrapper {
    display: inline-block;
    padding-top: 1rem;
    padding-right: .375rem;
    width: 9.625rem;
    position: relative;
    -webkit-order: 1;
    -ms-flex-order: 1;
    order: 1;
}
.event-calendar .result-card__date-wrapper .result-card__event-date, .event-calendar .result-card__date-wrapper .result-card__time {
    display: block;
}
.event-calendar .result-card__date-wrapper .result-card__event-date {
    font-size: 2rem;
    line-height: 2rem;
    color: #c4d82d;
    margin-bottom: .3125rem;
}
.event-calendar .result-card__date-wrapper .result-card__time {
    line-height: 1rem;
    color: #c4d82d;
    margin-left: 0;
}
.event-calendar .result-card__event-issue {
    display: inline-block;
    font-size: .75rem;
    line-height: 1.1875rem;
    letter-spacing: -.00625rem;
    color: #bee7f9;
    vertical-align: top;
    margin-left: 1.25rem;
    margin-top: 1.5625rem;
    max-width: 45%;
    -webkit-order: 2;
    -ms-flex-order: 2;
    order: 2;
}
.event-calendar .result-card__info-wrapper {
    -webkit-order: 3;
    -ms-flex-order: 3;
    order: 3;
    width: 100%}
.event-calendar .result-card__title {
    font-family: gotham a, gotham b;
    font-weight: 400;
    font-size: .875rem;
    line-height: 1.1875rem;
    color: #fff;
    margin: 1.875rem 0 1.5625rem;
}
.event-calendar .result-card__place, .event-calendar .result-card__place a {
    letter-spacing: -.00625rem;
    color: #bee7f9;
}
@media screen and (min-width:1024px) {
.event-calendar .result-card__event {
    padding: 1.625rem 2.3125rem 0;
    height: 12.8125rem;
}
.event-calendar .result-card__event:after {
    height: auto;
    bottom: initial;
    left: 15.3125rem;
    top: 3.9375rem;
    bottom: 0;
}
.event-calendar .result-card__date-wrapper, .event-calendar .result-card__event-issue {
    padding-left: 0;
    margin-left: 0;
}
.event-calendar .result-card__event-issue {
    margin: 0;
    -webkit-order: 1;
    -ms-flex-order: 1;
    order: 1;
    max-width: none;
    width: 100%;
    height: 2.5rem;
}
.event-calendar .result-card__date-wrapper {
    -webkit-order: 2;
    -ms-flex-order: 2;
    order: 2;
    padding-top: 0;
    position: static;
    width: 13.0625rem;
    margin-right: 0;
}
.event-calendar .result-card__date-wrapper .result-card__event-date {
    font-size: 3.125rem;
    line-height: .9;
}
.event-calendar .result-card__time, .event-calendar .result-card__details-wrapper {
    position: absolute;
    bottom: 1.375rem;
    height: 2.5rem;
    width: auto;
}
.event-calendar .result-card__info-wrapper {
    -webkit-order: 3;
    -ms-flex-order: 3;
    order: 3;
    width: 69.14722%}
.event-calendar .result-card__info-wrapper .result-card__title {
    margin: 0;
    font-size: 1.375rem;
    line-height: 1.6875rem;
    position: relative;
    top: 0;
}
.event-calendar .result-card__info-wrapper .result-card__place, .event-calendar .result-card__info-wrapper .result-card__keynote-wrapper {
    display: inline-block;
    vertical-align: top;
    position: relative;
}
.event-calendar .result-card__info-wrapper .result-card__place {
    width: 8.75rem;
}
.event-calendar .result-card__info-wrapper .result-card__keynote-wrapper {
    font-family: gotham a, gotham b;
    font-weight: 400;
    left: .625rem;
    font-size: .75rem;
    max-width: 50%}
.event-calendar .result-card__info-wrapper .result-card__keynote-eyebrow {
    color: #fff;
}
.event-calendar .result-card__info-wrapper .result-card__keynote-speakers, .event-calendar .result-card__info-wrapper .result-card__keynote-speakers a {
    color: #bee7f9;
    font-weight: 400;
}
}



</style>

app/views/events/new.html.erb
<% provide(:events_active, 'active') %>

<div class="bg-color">
	<%= render 'eventsnav' %>
	<div class="container">

		<br/>
		<div class="wrapper-bc">
			<section class="header-bc">

  				<div class="logo-and-nav-wrap">
			
					<div class="site-nav-wrap">
         				<nav class="nav-bc">
					
							<div class="single-breadcrumb-wrap">
								<span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc"><a href="/">Home</a></span>
							</div>
							<div class="single-breadcrumb-wrap">
								<span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc"><%= link_to 'Events', events_path %></span>
							</div>							
           					<div class="single-breadcrumb-wrap">
								<span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc">New</span>
							</div>							
						</nav>
					</div>
				</div>
			</section>
  		</div>	

		<br/>

		<%= form_for @event, :html => {:multipart => true} do |f| %>

			<div class="form-group row">
				<%= f.label "event_title:" %>
				<div class="col-10">
					<%= f.text_field :event_title %>
				</div>
			</div>

			<div class="form-group row">
				<%= f.label "event_body:" %>
				<div class="col-10">
					<%= f.text_field :event_body %>	
				</div>
			</div>
				
			<div class="form-group row">
				<%= f.label "event_date:" %>
				<div class="col-10">
					<%= f.text_field :event_date %>
				</div>
			</div>

			<div class="form-group row">
				<%= f.label "event_time:" %>
				<div class="col-10">
					<%= f.time_select :event_time %>
				</div>
			</div>

			<div class="form-group row">
				<%= f.label "event_location:" %>
				<div class="col-10">
					<%= f.text_field :event_location %>	
				</div>
			</div>

			<div class="form-group row">
				<div class="col-10">
					<%= f.submit "Submit", class: "btn btn-primary" %>
				</div>
			</div>
			<br/>
			<br/>

		<% end %>
	</div>
</div>

app/views/events/show.html.erb
<% provide(:events_active, 'active') %>

<div class="bg-color">
	<%= render 'eventsnav' %>
	<div class="container">
		<br/>

		<div class="wrapper-bc">
			<section class="header-bc">

  				<div class="logo-and-nav-wrap">
			
					<div class="site-nav-wrap">
         				<nav class="nav-bc">
					
							<div class="single-breadcrumb-wrap">
								<span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc"><a href="/">Home</a></span>
							</div>
							<div class="single-breadcrumb-wrap">
								<span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc"><%= link_to 'Events', events_path %></span>
							</div>							
           					<div class="single-breadcrumb-wrap">
								<span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc"><%= @event.event_title %></span>
							</div>							
						</nav>
					</div>
				</div>
			</section>
  		</div>		
		

		<a href="http://twitter.com/home?status=<%= request.original_url %>" title="Share on Twitter" target="_blank" class="btn btn-twitter"><i class="fa fa-twitter"></i> Twitter</a>
		<a href="https://www.facebook.com/sharer/sharer.php?u=<%= request.original_url %>" title="Share on Facebook" target="_blank" class="btn btn-facebook"><i class="fa fa-facebook"></i> Facebook</a>
		<a href="https://plus.google.com/share?url=<%= request.original_url %>" title="Share on Google+" target="_blank" class="btn btn-googleplus"><i class="fa fa-google-plus"></i> Google+</a>
		<a href="http://www.linkedin.com/shareArticle?mini=true&url=&title=&summary=<%= request.original_url %>" title="Share on LinkedIn" target="_blank" class="btn btn-linkedin"><i class="fa fa-linkedin"></i> LinkedIn</a>
		<a href="https://www.google.com/bookmarks/mark?op=edit&output=popup&bkmk=<%= request.original_url %>&title=<%= @event.event_title %>" title="Add to Google Bookmark" target="_blank" class="btn btn-bookmark"><i class="fa fa-bookmark"></i> Google Bookmark</a>
		<br/>
		<br/>

		<% if user_signed_in? %>
			<% if policy(:event).edit? %>
				<small class="pull-right"><%= link_to "Delete", event_path(@event.id), method: :delete,
				data: { confirm: "Are you sure?" }, :style => 'text-decoration: none;' %></small>
				<small class="pull-right">
					<%= link_to edit_event_path, :style => 'text-decoration: none;' do %>
						Edit &nbsp;
					<% end %>
				</small>
			<% end %>
		<% end %>

		<div class="container">
			<div class="row">
				<p><%= @event.event_title %></p>
				<p><%= @event.event_body %></p>
				<p><%= @event.event_date %></p>	
				<p><%= @event.event_time.strftime("%H:%M") %></p>	
				<p><%= @event.event_location %></p>	
			</div>
		</div>
	</div>
</div>