config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  get 'upload' => 'images#new', :as => "upload"
  get 'membership' => 'memberships#new'
  get 'events/calendar' => 'events#calendar'
  resources :albums, :images, :events, :posts, :users
  root 'albums#index'
  get '/test' => 'memberships#test'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
	has_attached_file :cover_image
	validates_attachment_content_type :cover_image, content_type: /\Aimage\/.*\z/
	has_many :images, :dependent => :delete_all
	validates :name, presence: true, uniqueness: true
	validates :description, presence: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :check_authorize, only: [:new, :edit, :update, :destroy, :create]

  def index
    @albums = Album.all
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      flash[:notice] = "Album Created!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @album = Album.find(params[:id])
    @albums = Album.all
    @images = @album.images
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      flash[:notice] = "Album Updated!"
      redirect_to album_path(params[:id])
    else
      render 'edit'
    end
  end

  def destroy
    @album  = Album.find(params[:id])
    @album.destroy

    redirect_to root_path
  end

  def show
    @album = Album.find(params[:id])
    @images = @album.images.paginate(:page => params[:page], :per_page => 20)
  end

  private

  def album_params
    params.require(:album).permit(:name, :description, :cover_image)
  end

  def check_authorize
    authorize OpenStruct.new(policy_class: AlbumPolicy, current_user: current_user)
  end  
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/edit.html.erb
<div class="bg-color">
	<div class="container">
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>

		<div class="wrapper-bc">
			<section class="header-bc">

  				<div class="logo-and-nav-wrap">
			
					<div class="site-nav-wrap">
         				<nav class="nav-bc">
					
							<div class="single-breadcrumb-wrap">
								<span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc"><a href="/">Home</a></span>
							</div>
							<div class="single-breadcrumb-wrap">
								<span class="sep">
									<i class="fa fa-caret-right"></i>
								</span>
								<%= link_to 'Albums', albums_path, :class => "breadcrumb-bc" %>
							</div>
							<div class="single-breadcrumb-wrap">
								<span class="sep">
									<i class="fa fa-caret-right"></i>
								</span>
								<%= link_to @album.name, album_path(@album.id), :class => "breadcrumb-bc" %>
							</div>					
           					<div class="single-breadcrumb-wrap">
								<span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc">Edit</span>
							</div>
						</nav>
					</div>
				</div>
			</section>
  		</div>

  		<br/>
  		<h2>Edit <%= @album.name %></h2>
		<%= form_for @album do |f| %>
		<br/>
			<% if @album.errors.any? %>
			    <% @album.errors.full_messages.each do |msg| %>
			    	<div class="alert alert-danger"><%= msg %></div>
			    <% end %>
			<% end %>

			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class:"form-control" %>
			</div>

		    <div class="form-group">
		     	<%= f.label :description %>
				<%= f.text_field :description, class:"form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :cover_image %>
				<%= f.file_field :cover_image %>
			</div>
			
			<div class="form-group">
				<% if @album.cover_image.present? %>
		            <%= (image_tag @album.cover_image.url, style: 'height: 210px; display: block;') %>
				<% else %>
		            <p>There are no images!</p>
				<% end %>
			</div>

			
			<%= f.submit "Submit", class:"btn btn-primary" %>
			<%= link_to "Cancel", album_path, class:"btn btn-primary", style:"color: #fff;" %>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
		<% end %>

		<div id="edit_images">
			<% if @images.exists? %>
				<% @images.each_slice(4) do |image| %>
					<div class="row">
						<% image.each do |img| %>
							<div class="col-md-3" style="margin-bottom: 20px;">
								<%= image_tag img.image.url, :style => 'height: 250px;width:100%;' %>
								<center>
									<%= link_to "Edit", edit_image_path(img.id), :style => 'text-decoration: none;' %>
										<%= link_to "Delete", image_path(img), :class => 'delete',method: :delete, :style => 'text-decoration: none;',data: { confirm: "Are you sure?" } %>
								</center>
							</div>
						<% end %>
					</div>
				<% end %>
			<% end %>
		</div>
		<br/>
	</div>
</div>

app/views/albums/index.html.erb
<div style="background-color: #f8f9fa;">
  <br />
  <br />
  <br />
  <br />
  <br />
</div>

<div class="container" style="background-color: #f8f9fa;">
  <% if user_signed_in? %>
    <% if @albums.exists? %>
      <% if policy(:album).edit? %>
        <%= link_to "Upload Photo", upload_path, :class => 'pull-right', :style => 'text-decoration: none;' %>
        <%= link_to new_album_path, :class => 'pull-right', :style => 'text-decoration: none;' do %>
        Add Album&nbsp;&nbsp;&nbsp;
        <% end %>
      <% else %>
        <% if policy(:album).edit? %>
          <%= link_to "Add Album", new_album_path, :class => 'pull-right' %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="album py-5 bg-light">
	<div class="container">
		<div class="row">
			<% @albumNav.each do |album| %>
				<div class="col-md-3">
          			<div class="card mb-4 box-shadow shadow-sm">
          				<% if album.cover_image.present? %>
                    <%= link_to (image_tag album.cover_image.url, style: 'height: 210px; width: 100%; display: block;'), album_path(album.id) %>
						      <% else %>
                    <%= link_to (image_tag "Thumbnail.png", style: 'height: 210px; width: 100%; display: block;'), album_path(album.id) %>
						      <% end %>
            			<div class="card-body">

              				<p class="card-text"><%= truncate(album.description, length: 75) %></p>
              				<div class="d-flex justify-content-between align-items-center">
                				<div class="btn-group">
                          <%= link_to "View", album_path(album.id), class:'btn btn-sm btn-outline-secondary' %>
                          <% if user_signed_in? %>
                            <% if policy(:album).edit? %>
                              <%= link_to "Edit", edit_album_path(album.id), class:'btn btn-sm btn-outline-secondary' %>
                            <% end %>
                          <% end %>
                				</div>
                				<small class="text-muted"><%= album.created_at.strftime("%-b %-d %Y") %></small>
              				</div>
            			</div>
          			</div>
           		</div>
          	<% end %>
      	</div>
	</div>
  <br />
</div>

<div class="digg_pagination justify-content-center">
  <%= will_paginate @albumNav %>
</div>

app/views/albums/new.html.erb
<div class="bg-color">
  <div class="container">
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <div class="wrapper-bc">
      <section class="header-bc">

          <div class="logo-and-nav-wrap">
      
          <div class="site-nav-wrap">
            <nav class="nav-bc">
          
              <div class="single-breadcrumb-wrap">
                <span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc"><a href="/">Home</a></span>
              </div>
              <div class="single-breadcrumb-wrap">
                <span class="sep">
                  <i class="fa fa-caret-right"></i>
                </span>
                <%= link_to 'Albums', albums_path, :class => "breadcrumb-bc" %>
              </div>         
              <div class="single-breadcrumb-wrap">
                <span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc">New Album</span>
              </div>
            </nav>
          </div>
        </div>
      </section>
      </div>    

    <br/>

    <%= form_for @album, html: { multipart: true } do |form| %>

      <div class="form-group row">
        <%= form.label "Name:" %>
        <div class="col-10">
          <%= form.text_field :name %>
        </div>
      </div>
  
      <div class="form-group row">
        <%= form.label "Description:" %>
        <div class="col-10">
          <%= form.text_field :description %>  
        </div>
      </div>

      <div class="form-group row">
        <%= form.label "Cover Image:" %>
        <div class="col-10">
          <%= form.file_field :cover_image %>
        </div>
      </div>
      
      <%= form.submit "Submit", class: "btn btn-primary" %>

      <br/>
      <br/>
    <% end %>
  </div>
</div>

app/views/albums/show.html.erb
<div class="bg-color">
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<div class="container">

		<div class="wrapper-bc">
			<section class="header-bc">

  				<div class="logo-and-nav-wrap">
			
					<div class="site-nav-wrap">
         				<nav class="nav-bc">
					
							<div class="single-breadcrumb-wrap">
								<span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc"><a href="/">Home</a></span>
							</div>
							<div class="single-breadcrumb-wrap">
								<span class="sep">
									<i class="fa fa-caret-right"></i>
								</span>
								<%= link_to 'Albums', albums_path, :class => "breadcrumb-bc" %>
							</div>					
           					<div class="single-breadcrumb-wrap">
								<span class="sep"><i class="fa fa-caret-right"></i></span> <span class="breadcrumb-bc"><%= @album.name %></span>
							</div>
						</nav>
					</div>
				</div>
			</section>
  		</div>

		<div class="float-right">
			<div id="social-media-icons">
				<a href="http://www.linkedin.com/shareArticle?mini=true&url=&title=&summary=<%= request.original_url %>" title="Share on LinkedIn" target="_blank" style="color:#666">
					<i class="fa fa-linkedin fa-2x"></i>
				</a>
			</div>
			<div id="social-media-icons">
				<a href="http://twitter.com/home?status=<%= request.original_url %>" title="Share on Twitter" target="_blank" style="color:#666">
					<i class="fa fa-twitter fa-2x"></i>
				</a>
			</div>
			<div id="social-media-icons">
				<a href="https://www.facebook.com/sharer/sharer.php?u=<%= request.original_url %>" title="Share on Facebook" target="_blank" style="color:#666">
					<i class="fa fa-facebook fa-2x"></i>
				</a>
			</div>
			<div id="social-media-icons">
				<a href="https://plus.google.com/share?url=<%= request.original_url %>" title="Share on Google+" target="_blank" style="color:#666">
					<i class="fa fa-google-plus fa-2x"></i>
				</a>
			</div>
		</div>

		<div class="container gallery-container">
			<% if user_signed_in? %>
				<% if policy(:album).edit? %>
					<small class="pull-right"><%= link_to "Delete", album_path(@album.id), method: :delete,
						data: { confirm: "Are you sure?" }, :style => 'text-decoration: none;' %></small>
					<small class="pull-right">
						<%= link_to edit_album_path, :style => 'text-decoration: none;' do %>
							Edit &nbsp;
						<% end %>
					</small>
					<small class="pull-right">
						<%= link_to upload_path, :style => 'text-decoration: none;' do %>
							Add &nbsp;
						<% end %>
					</small>
				<% end %>
			<% end %>
		    <h1><%= @album.name %></h1>
		    <p class="page-description text-center"><%= @album.description %></p>
		    <div class="tz-gallery">
		        <div class="row">
		        	<% if @images.exists? %>
		        		<% @images.each do |img| %>
		            		<div class="col-sm-6 col-md-3">
		                		<div class="thumbnail">
		                    		<a class="lightbox" href="<%= img.image.url %>">
		                        		<img src="<%= img.image.url %>" alt="Park" style="display: block;width: 100%;height: 250px;">
		                    		</a>
		                    		<% if img.image_title.length>0 or img.image_description.length>0 %>
			                    		<div class="caption">
			                    			<% if img.image_title.length>0 %>
			                        			<h3><%= img.image_title %></h3>
			                        		<% end %>
			                        		<% if img.image_description.length>0 %>
			                        			<p><%= truncate(img.image_description, length:125) %></p>
			                        		<% end %>
			                    		</div>
			                    	<% end %>
		                		</div>
		            		</div>
		            	<% end %>
		            <% else %>
		            	<p>There are no images!</p>
		            <% end %>
		        </div>
		    </div>
		</div>
	</div>
</div>

<div class="digg_pagination justify-content-center">
  <%= will_paginate @images %>
</div>

<script>
    baguetteBox.run('.tz-gallery');
</script>