config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  get 'upload' => 'images#new', :as => "upload"
  get 'membership' => 'memberships#new'
  get 'events/calendar' => 'events#calendar'
  resources :albums, :images, :events, :posts, :users
  root 'albums#index'
  get '/test' => 'memberships#test'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="container py-5">
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="d-block mb-2"><circle cx="12" cy="12" r="10"></circle><line x1="14.31" y1="8" x2="20.05" y2="17.94"></line><line x1="9.69" y1="8" x2="21.17" y2="8"></line><line x1="7.38" y1="12" x2="13.12" y2="2.06"></line><line x1="9.69" y1="16" x2="3.95" y2="6.06"></line><line x1="14.31" y1="16" x2="2.83" y2="16"></line><line x1="16.62" y1="12" x2="10.88" y2="21.94"></line></svg>
      <small class="d-block mb-3">&copy; 2017-2018</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Cool stuff</a></li>
        <li><a class="text-muted" href="#">Random feature</a></li>
        <li><a class="text-muted" href="#">Team feature</a></li>
        <li><a class="text-muted" href="#">Stuff for developers</a></li>
        <li><a class="text-muted" href="#">Another one</a></li>
        <li><a class="text-muted" href="#">Last time</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Resource</a></li>
        <li><a class="text-muted" href="#">Resource name</a></li>
        <li><a class="text-muted" href="#">Another resource</a></li>
        <li><a class="text-muted" href="#">Final resource</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Business</a></li>
        <li><a class="text-muted" href="#">Education</a></li>
        <li><a class="text-muted" href="#">Government</a></li>
        <li><a class="text-muted" href="#">Gaming</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Team</a></li>
        <li><a class="text-muted" href="#">Locations</a></li>
        <li><a class="text-muted" href="#">Privacy</a></li>
        <li><a class="text-muted" href="#">Terms</a></li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top nav-bg-color box-shadow" id="global-nav" style="background-color: #0f2a38;">
	<%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>

	<div class="container">
		<div class="container d-flex justify-content-between">
			<a class="navbar-brand" href="/"><h1>WYCAT</h1></a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
	  		</button>

	  		<div class="collapse navbar-collapse navprimary" id="navbarSupportedContent">
	    		<ul class="navbar-nav ml-auto">
	      			<li class="nav-item #{yield(:gallery_active)}">
	      				<%= link_to 'GALLERY', albums_path , class:"nav-link #{yield(:gallery_active)}" %>
	      			</li>
	      			<li class="nav-item">
	      				<%= link_to 'NEWS', posts_path , class:"nav-link #{yield(:news_active)}" %>
	      			</li>
	      			<li class="nav-item">
	      				<%= link_to 'MEMBERSHIP', membership_path, class:"nav-link #{yield(:membership_active)}" %>
	      			</li>
	      			<li class="nav-item">
	      				<%= link_to 'EVENTS', events_path, class:"nav-link #{yield(:events_active)}" %>
	      			</li>
	      			<% if user_signed_in? %>
				      	<li class="nav-item dropdown">
				        	<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				          <%= current_user.email %>
				        	</a>
				       		<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				       			<% if current_user.admin? %>
				          			<%= link_to 'Users', users_path, class: "dropdown-item" %>
						        	<div class="dropdown-divider"></div>				          			
				          		<% end %>
				          		<%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
				        	</div>
				      	</li>
			      	<% end %>	      				      				      
	    		</ul>
	  		</div>
		</div>
  	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WYCAT Global</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
      <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>